### ISSUE TITLE
Límites GH actions

### ISSUE THREAD

**Issue by yagueto** [JaimeObregon/metanavarra#1]
https://github.com/JaimeObregon/metanavarra/blob/39693fa8b55ddf1f4332852fc0b2e310baa80a78/.github/workflows/fetch.yml#L13

[De acuerdo con la documentación ](https://docs.github.com/es/actions/learn-github-actions/usage-limits-billing-and-administration#), esos límites de 2000 mins son solo para repos privados. Podemos tener más logs si queremos 😄

**Comment by JaimeObregon** [comment]
¡Bien visto, @yagueto! Ya está modificado. 🙂
